### ISSUE TITLE
Concurrency safety

### ISSUE THREAD

**Issue by nazwa** [fundary/paypal#3]
Hello! 

One of the todos in your readme is "Concurrency safety by utilizing PayPal-Request-Id". Do you think the current implementation might be unsafe for use in webapps with high transaction volume? Apart from that, great library!

**Comment by pengux** [comment]
It may or it may not depending on Paypal API performance. But according to its documentation, using Paypal-Request-Id will decrease the risk of duplicate transactions (https://developer.paypal.com/docs/api/). I would suggest you do some tests in your environment and find out.

**Comment by nazwa** [comment]
Thanks, I'll look into it. Thought it was more to do with the library itself and maybe some race conditions.
